[project]
name = "ztrade"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "akshare==1.17.7",
    "mootdx==0.11.7",
    "pandas==2.3.0",
    "scipy==1.14.1",
    "tqdm==4.66.4",
    "tushare==1.4.21",
]
